name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build APK
      run: |
        # إعداد الملف
        buildozer init
        
        # تعديل buildozer.spec بشكل كامل
        sed -i 's/title = .*/title = Dobli App/' buildozer.spec
        sed -i 's/package.name = .*/package.name = dobli/' buildozer.spec
        sed -i 's/package.domain = .*/package.domain = com.marcbigard5/' buildozer.spec
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        sed -i 's/# android.api = 33/android.api = 33/' buildozer.spec
        sed -i 's/# android.minapi = 24/android.minapi = 24/' buildozer.spec
        sed -i 's/# android.sdk = 20/android.sdk = 33/' buildozer.spec
        sed -i 's/requirements = .*/requirements = python3==3.10.12,kivy==2.3.0/' buildozer.spec
        
        # بناء التطبيق
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Dobli-App
        path: /home/user/host/**/bin/*.apk
